version: '3'

services:
  # React App
  web-be:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx serve web-be
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    networks:
      - default

  # React App
  web-fe:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    volumes:
      - .:/app
    command: sh -c "npx prisma generate --schema=./apps/web-fe/prisma/schema.prisma && nx serve web-fe"
    environment:
      - NEXT_PUBLIC_NX_API_URL=http://localhost:3000
    depends_on:
      - web-be
    ports:
      - 4300:4200
    networks:
      - default
volumes:
  mono-node-modules: null